travis:
  secure:
    BINSTAR_TOKEN: EVzQEJaOV0+qjwvQThkBvHiiTHvcTT2uX9rkuqcNzU5JVL1h3QtIP63kVKrFbgkzchdXE10dYIZ5o/L1yBGLXuYNJj6bkLLN4GF9PPH9ZycGo0j36zW//mmISQhd4ph0NDewqekecrmGqB94IKGIfTkRu+nu1GSdLpk+IJJz+H2g+0xRvBQSn1opKN1ujHKEyqyixSlURBfYq/8t5X3viJ8O9QZETUrTMz3o/UspMRRvXEH3eymwcVSaZZZsb3KbeNXxZo9Cizk15pl+7iq31lZ8/hpV+P+48u7bPyUg8KDIpLohp9XeJ0/QjiowTmNrqpNe82s0+KbLl9Nvtq9cFo9EfAcki6gw7NscWZN4ukCxLCjih5TRK9fxGw6lCV3GLJqBIhfi2GllLtGHng0pRKE5+noDsqJYml4xDjOPQQ2SU0E+dH9m1wguGuWIke1tupwP9QT0gCJzKarZzwZMNiBxMbLMbmYDnwmPQhxvRd9jCvyRM3npjr5XwygZtfuhNy7t1t9WBPLKWWvlCcITI9HgniqLPmh5ocb8vDTM6t5zBpcXBwuetOf6RvPfRVcrQN//nPuGPX4cdDnjrMlAXqFFTqTC1W2jSqtHMrCJ8MNcu0xM3Zs9w1W+eXxr6VQPdYWls2nZ/dfq1JeU2BKEiupHRXvP6R9qJi17GxwSAWA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
