appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JH1bMKhtI3MraNF9mmEHpQRPjB9XKhRj/QqMCpnTxdXBAT0JAKbcrdZxRAH7smTzYIyO0oSw5EFT7Jd8x+lJReU5+Ub2YNs5v7tSMJGZhoRzJGZVc2aj+CKN8ZuxNK7JcAZ9jzhckrGONfvil6o5tiTLp+lzqIrfLXL1fMdIZc/3VnQDdrvmmw0UzM1DHaUzvXGxnFQSXAUNQE3nehcihB7sZT6/BZ89NH6ZSqGM1xxfEPF0K0pMxMXU5+IoznbsnNu1UDEfTCAmcs7JQdnTK/bcgbBEX8wJEvKZhk4TOwQFhUIcZVCgPeMPd/VYviYcb6ip5U8Ttub5TTc1JvMN3SGEMYyzfWuBgyX2/PA2vFmsnNEETInENhSbF/5SPnqWSmcQ32mQm19yhduU70CGX6Z2s13iNXyNsp5h3sjUeq6y8tROU6Xzxta2RUTNDzHMoAbJMEeBen8nnMxJQt3z7M1TVb1sOhOtrveq05UgT705UaptB4ty4jgNq0fKk0gcuc1dh2PxzaxiE29Xfs4LMogTvqYFOUca7lla/vt4fK3lV8pZ4hgd7tiJvYyk+XvYn1Uyd30oKRlo5APdmQdvGCvyzJL4+4nTtDM9nFqiNtty7+4MahIr+eduIJ0vLJfG4i3S6ODP1HevqY2U5uTUsSKHeMB3IYslQ7hmx8eYSp4=}
conda_forge_output_validation: false
